logging:
  config: classpath:logback-converter.xml

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_ADDRESS}/springboot_demo?useSSL=false&autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
