server:
  port: 80
  tomcat:
    threads:
      max: 500
    uri-encoding: UTF-8
    basedir: ./tomcat
    accesslog:
      pattern: combined
      enabled: true
      rename-on-rotate: true
      request-attributes-enabled: true
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_ADDRESS:127.0.0.1:2202}/${DB_NAME:springboot_demo}?useSSL=false&autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123132}
  config:
    import:
      - classpath:cloud_api.yml
  application:
    name: aigc-sd-qc
  gson:
    disableHtmlEscaping: true
  jackson.default-property-inclusion: non_null
logging:
  level:
    root: ERROR
    org.springframework: INFO
    com.yiyun: DEBUG
  config: classpath:logback-converter-local.xml